# Generated by Django 4.2.16 on 2025-07-14 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Food Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('serving_size', models.DecimalField(decimal_places=2, help_text='Default serving size in grams', max_digits=8)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fat_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbs_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fiber_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sugar_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sodium_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Data verification status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='foods.foodcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=500)),
                ('results_count', models.IntegerField(default=0)),
                ('search_type', models.CharField(choices=[('text', 'Text Search'), ('image', 'Image Recognition'), ('barcode', 'Barcode Scan')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='foods_foods_user_id_574a21_idx'), models.Index(fields=['search_type'], name='foods_foods_search__45a9f0_idx'), models.Index(fields=['created_at'], name='foods_foods_created_8078bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='FoodAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='foods.food')),
            ],
            options={
                'verbose_name_plural': 'Food Aliases',
                'indexes': [models.Index(fields=['alias'], name='foods_fooda_alias_4fa10a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='foods_food_name_8eac09_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category'], name='foods_food_categor_87d016_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['created_by'], name='foods_food_created_ad8412_idx'),
        ),
    ]
