# Generated by Django 4.2.16 on 2025-07-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="food",
            name="foods_food_categor_87d016_idx",
        ),
        migrations.RemoveField(
            model_name="food",
            name="category",
        ),
        migrations.AddField(
            model_name="food",
            name="usda_fdc_id",
            field=models.CharField(
                blank=True,
                help_text="USDA FoodData Central ID",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["usda_fdc_id"], name="foods_food_usda_fd_29b569_idx"
            ),
        ),
        migrations.DeleteModel(
            name="FoodCategory",
        ),
    ]
