# Generated by Django 4.2.16 on 2025-07-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_remove_food_categories"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["barcode"], name="foods_food_barcode_a0aca0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("barcode__isnull", False), models.Q(("barcode", ""), _negated=True)
                ),
                fields=("barcode",),
                name="unique_barcode_when_not_null",
            ),
        ),
    ]
