# Generated by Django 4.2.16 on 2025-07-29 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("foods", "0003_food_foods_food_barcode_a0aca0_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_associations",
                        to="foods.food",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_foods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="foods_userf_user_id_086763_idx"
                    ),
                    models.Index(
                        fields=["food"], name="foods_userf_food_id_414691_idx"
                    ),
                    models.Index(
                        fields=["added_at"], name="foods_userf_added_a_54124f_idx"
                    ),
                ],
                "unique_together": {("user", "food")},
            },
        ),
    ]
