# Generated by Django 4.2.16 on 2025-07-29 20:31

from django.db import migrations


def populate_user_foods(apps, schema_editor):
    """Create UserFood associations for existing user-created foods"""
    Food = apps.get_model("foods", "Food")
    UserFood = apps.get_model("foods", "UserFood")

    # Get all foods that have a created_by user
    user_created_foods = Food.objects.filter(created_by__isnull=False)

    # Create UserFood associations for each user-created food
    user_foods_to_create = []
    for food in user_created_foods:
        user_foods_to_create.append(UserFood(user=food.created_by, food=food))

    # Bulk create all UserFood associations
    if user_foods_to_create:
        UserFood.objects.bulk_create(user_foods_to_create, ignore_conflicts=True)


def reverse_populate_user_foods(apps, schema_editor):
    """Remove UserFood associations (reverse operation)"""
    UserFood = apps.get_model("foods", "UserFood")
    UserFood.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0004_userfood"),
    ]

    operations = [
        migrations.RunPython(populate_user_foods, reverse_populate_user_foods),
    ]
