# Generated by Django 4.2.16 on 2025-07-14 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("foods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "meal_type"],
            },
        ),
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_calories",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_protein",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_fat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_carbs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_fiber",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "weight_recorded",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight recorded for the day",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MealFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, help_text="Quantity in grams", max_digits=8
                    ),
                ),
                ("calories", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "protein",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "fat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foods.food"
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_foods",
                        to="meals.meal",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["meal"], name="meals_mealf_meal_id_6bec07_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["user", "date"], name="meals_meal_user_id_9c94ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["user", "meal_type"], name="meals_meal_user_id_b5db63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailysummary",
            index=models.Index(
                fields=["user", "date"], name="meals_daily_user_id_2342d4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailysummary",
            unique_together={("user", "date")},
        ),
    ]
