# Generated by Django 4.2.16 on 2025-07-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
