[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn calorie_tracker.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/v1/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app/backend:$PYTHONPATH"