[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/v1/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app/backend:$PYTHONPATH"