"""
Django settings for calorie_tracker project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-006vdf%35^m0_sd%+jom_%4%=yd%5=dy&(3d83!((l30#*gs0^",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

# Parse ALLOWED_HOSTS from environment variable
ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1,*.railway.app,.up.railway.app",
    cast=lambda x: [h.strip() for h in x.split(",") if h.strip()],
)

# Allow all Railway hosts if RAILWAY_ENVIRONMENT is set
if "RAILWAY_ENVIRONMENT" in os.environ:
    ALLOWED_HOSTS.extend([".railway.app", ".up.railway.app"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "accounts",
    "foods",
    "meals",
    "images",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Custom logging middleware
    "calorie_tracker.middleware.RequestLoggingMiddleware",
    "calorie_tracker.middleware.PerformanceLoggingMiddleware",
    "calorie_tracker.middleware.SecurityLoggingMiddleware",
]

ROOT_URLCONF = "calorie_tracker.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "calorie_tracker.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


import dj_database_url


# Database configuration with Railway PostgreSQL troubleshooting
def get_database_config():
    """Get database configuration with fallback options"""
    import logging

    logger = logging.getLogger("startup")

    # Print environment variables for debugging
    logger.info("=== DATABASE DEBUG INFO ===")
    database_env_vars = {
        k: v for k, v in os.environ.items() if "DATABASE" in k or "PG" in k
    }
    for key, value in database_env_vars.items():
        if "PASSWORD" in key:
            logger.info(f"{key}: [HIDDEN]")
        else:
            logger.info(f"{key}: {value}")
    logger.info("========================")

    if "DATABASE_URL" in os.environ:
        # Production: Use PostgreSQL via DATABASE_URL (Railway/Heroku)
        database_url = os.environ.get("DATABASE_URL")
        if database_url:
            logger.info(
                f"Using DATABASE_URL: {database_url.split('@')[0]}@[HOST_HIDDEN]"
            )
            try:
                parsed_db = dj_database_url.parse(database_url)
                logger.info(
                    f"Parsed database config - Engine: {parsed_db.get('ENGINE')}, Name: {parsed_db.get('NAME')}, Host: {parsed_db.get('HOST')}, Port: {parsed_db.get('PORT')}"
                )

                # Add connection options for Railway
                parsed_db.update(
                    {
                        "OPTIONS": {
                            "connect_timeout": 60,
                            "keepalives_idle": 600,
                            "keepalives_interval": 30,
                            "keepalives_count": 3,
                        },
                        "CONN_MAX_AGE": 60,
                        "CONN_HEALTH_CHECKS": True,
                    }
                )

                logger.info(
                    "Database configuration loaded successfully with Railway PostgreSQL options"
                )
                return {"default": parsed_db}
            except Exception as e:
                logger.error(f"Failed to parse DATABASE_URL: {e}")
                raise
        else:
            logger.error("DATABASE_URL environment variable is set but empty")
            raise ValueError("DATABASE_URL environment variable is set but empty")

    elif "RAILWAY_ENVIRONMENT" in os.environ:
        # Railway environment without DATABASE_URL (fallback to individual variables)
        logger.info("Using individual PostgreSQL environment variables")
        db_config = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("PGDATABASE", "railway"),
            "USER": os.environ.get("PGUSER", "postgres"),
            "PASSWORD": os.environ.get("PGPASSWORD", ""),
            "HOST": os.environ.get("PGHOST", "localhost"),
            "PORT": os.environ.get("PGPORT", "5432"),
            "OPTIONS": {
                "connect_timeout": 60,
                "keepalives_idle": 600,
                "keepalives_interval": 30,
                "keepalives_count": 3,
            },
            "CONN_MAX_AGE": 60,
            "CONN_HEALTH_CHECKS": True,
        }
        logger.info(
            f"PostgreSQL config - Host: {db_config['HOST']}, Port: {db_config['PORT']}, DB: {db_config['NAME']}, User: {db_config['USER']}"
        )
        return {"default": db_config}
    else:
        # Development: Use SQLite
        logger.info("Using SQLite for development")
        return {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }


DATABASES = get_database_config()

# Add startup completion logging
import logging

startup_logger = logging.getLogger("startup")
startup_logger.info("Django settings configuration completed successfully")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Use WhiteNoise for static file serving in production
if not DEBUG or "RAILWAY_ENVIRONMENT" in os.environ:
    if "whitenoise.middleware.WhiteNoiseMiddleware" not in MIDDLEWARE:
        MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
else:
    # Development: Use default static files storage
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 20,
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# CORS Settings - Use environment variable for flexibility
# Parse CORS_ALLOWED_ORIGINS from environment variable or use defaults
default_cors_origins = "http://localhost:3000,http://127.0.0.1:3000"
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default=default_cors_origins,
    cast=lambda x: [
        origin.strip().strip('"').strip("'")
        for origin in x.replace("[", "").replace("]", "").split(",")
        if origin.strip()
    ],
)

# Also support FRONTEND_URL for single domain configuration
frontend_url = config("FRONTEND_URL", default=None)
if frontend_url and frontend_url not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(frontend_url)

CORS_ALLOW_CREDENTIALS = True

# Allow standard headers and streaming-specific headers
CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "cache-control",
    "x-requested-with",
]

# Allow additional methods for streaming
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

# Media files for image uploads

MEDIA_URL = "/media/"
# For Railway deployment, ensure media directory is writable
if "RAILWAY_ENVIRONMENT" in os.environ:
    MEDIA_ROOT = "/tmp/media"
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Custom user model
AUTH_USER_MODEL = "accounts.User"

from dotenv import load_dotenv

load_dotenv()
import json


# Handle API keys safely
try:
    USDA_API_KEYS = json.loads(os.getenv("USDA_API_KEYS", "[]"))
except (json.JSONDecodeError, TypeError):
    USDA_API_KEYS = []

try:
    OPENAI_API_KEYS = json.loads(os.getenv("OPENAI_API_KEYS", "[]"))
except (json.JSONDecodeError, TypeError):
    OPENAI_API_KEYS = []

# Ensure logs directory exists (only for local development)
if "RAILWAY_ENVIRONMENT" not in os.environ:
    LOGS_DIR = os.path.join(BASE_DIR, "logs")
    os.makedirs(LOGS_DIR, exist_ok=True)

# Logging Configuration
# LOGGING = {
# 	'version': 1,
# 	'disable_existing_loggers': False,
# 	'formatters': {
# 		'verbose': {
# 			'format': '[{levelname}] {asctime} {name} {process:d} {thread:d} - {message}',
# 			'style': '{',
# 		},
# 		'simple': {
# 			'format': '[{levelname}] {asctime} - {message}',
# 			'style': '{',
# 		},
# 		'detailed': {
# 			'format': '[{levelname}] {asctime} {name} {funcName}:{lineno} - {message}',
# 			'style': '{',
# 		},
# 	},
# 	'filters': {
# 		'require_debug_false': {
# 			'()': 'django.utils.log.RequireDebugFalse',
# 		},
# 		'require_debug_true': {
# 			'()': 'django.utils.log.RequireDebugTrue',
# 		},
# 	},
# 	'handlers': {
# 		'console': {
# 			'level': 'INFO',
# 			'filters': ['require_debug_true'],
# 			'class': 'logging.StreamHandler',
# 			'formatter': 'simple'
# 		},
# 		'console_debug': {
# 			'level': 'DEBUG',
# 			'filters': ['require_debug_true'],
# 			'class': 'logging.StreamHandler',
# 			'formatter': 'detailed'
# 		},
# 		'file_general': {
# 			'level': 'INFO',
# 			'class': 'logging.handlers.RotatingFileHandler',
# 			'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
# 			'maxBytes': 1024*1024*10,  # 10 MB
# 			'backupCount': 5,
# 			'formatter': 'verbose',
# 		},
# 		'file_debug': {
# 			'level': 'DEBUG',
# 			'class': 'logging.handlers.RotatingFileHandler',
# 			'filename': os.path.join(BASE_DIR, 'logs', 'debug.log'),
# 			'maxBytes': 1024*1024*10,  # 10 MB
# 			'backupCount': 3,
# 			'formatter': 'detailed',
# 		},
# 		'file_error': {
# 			'level': 'ERROR',
# 			'class': 'logging.handlers.RotatingFileHandler',
# 			'filename': os.path.join(BASE_DIR, 'logs', 'error.log'),
# 			'maxBytes': 1024*1024*10,  # 10 MB
# 			'backupCount': 5,
# 			'formatter': 'verbose',
# 		},
# 		'file_api': {
# 			'level': 'INFO',
# 			'class': 'logging.handlers.RotatingFileHandler',
# 			'filename': os.path.join(BASE_DIR, 'logs', 'api.log'),
# 			'maxBytes': 1024*1024*10,  # 10 MB
# 			'backupCount': 5,
# 			'formatter': 'verbose',
# 		},
# 		'file_openai': {
# 			'level': 'INFO',
# 			'class': 'logging.handlers.RotatingFileHandler',
# 			'filename': os.path.join(BASE_DIR, 'logs', 'openai.log'),
# 			'maxBytes': 1024*1024*10,  # 10 MB
# 			'backupCount': 3,
# 			'formatter': 'detailed',
# 		},
# 		'file_usda': {
# 			'level': 'INFO',
# 			'class': 'logging.handlers.RotatingFileHandler',
# 			'filename': os.path.join(BASE_DIR, 'logs', 'usda.log'),
# 			'maxBytes': 1024*1024*5,  # 5 MB
# 			'backupCount': 3,
# 			'formatter': 'detailed',
# 		},
# 	},
# 	'loggers': {
# 		'django': {
# 			'handlers': ['console', 'file_general'],
# 			'level': 'INFO',
# 			'propagate': False,
# 		},
# 		'django.request': {
# 			'handlers': ['console', 'file_api', 'file_error'],
# 			'level': 'WARNING',
# 			'propagate': False,
# 		},
# 		'django.db.backends': {
# 			# SQL logging: set ENABLE_SQL_DEBUG=true in .env to see all SQL queries
# 			'handlers': ['file_debug'] + (['console_debug'] if config('ENABLE_SQL_DEBUG', default=False, cast=bool) else []),
# 			'level': 'DEBUG' if config('ENABLE_SQL_DEBUG', default=False, cast=bool) else 'WARNING',
# 			'propagate': False,
# 		},
# 		# App-specific loggers
# 		'accounts': {
# 			'handlers': ['console', 'file_api'],
# 			'level': 'INFO',  # Reduced from DEBUG to INFO
# 			'propagate': False,
# 		},
# 		'foods': {
# 			'handlers': ['console', 'file_api'],
# 			'level': 'INFO',  # Reduced from DEBUG to INFO
# 			'propagate': False,
# 		},
# 		'meals': {
# 			'handlers': ['console', 'file_api'],
# 			'level': 'INFO',  # Reduced from DEBUG to INFO
# 			'propagate': False,
# 		},
# 		'images': {
# 			'handlers': ['console', 'file_api'],
# 			'level': 'INFO',  # Reduced from DEBUG to INFO
# 			'propagate': False,
# 		},
# 		# External service loggers
# 		'calorie_tracker.openai_service': {
# 			'handlers': ['console', 'file_openai'],
# 			'level': 'INFO',  # Reduced from DEBUG, keep important API calls
# 			'propagate': False,
# 		},
# 		'foods.usda_service': {
# 			'handlers': ['console', 'file_usda'],
# 			'level': 'INFO',  # Reduced from DEBUG
# 			'propagate': False,
# 		},
# 		# API request logging
# 		'api_requests': {
# 			'handlers': ['console', 'file_api'],
# 			'level': 'INFO',
# 			'propagate': False,
# 		},
# 		# Root logger for everything else
# 		'': {
# 			'handlers': ['console', 'file_general', 'file_error'],
# 			'level': 'INFO',
# 		},
# 	},
# }


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name} {process:d} {thread:d} - {message}",
            "style": "{",
        },
        "detailed": {
            "format": "[{levelname}] {asctime} {name} {funcName}:{lineno} - {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "gunicorn": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "gunicorn.error": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "gunicorn.access": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # App-specific loggers
        "accounts": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "foods": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "meals": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "images": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # External service loggers
        "calorie_tracker.openai_service": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "foods.usda_service": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Startup logging
        "startup": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Root logger for everything else
        "": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
