# Generated by Django 4.2.16 on 2025-07-14 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meals", "0001_initial"),
        ("foods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "file_path",
                    models.ImageField(
                        max_length=500, upload_to=images.models.upload_to_user_images
                    ),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("mime_type", models.CharField(max_length=100)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="meals.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FoodRecognitionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Recognition confidence (0-1)",
                        max_digits=5,
                    ),
                ),
                (
                    "estimated_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated quantity in grams",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False, help_text="User confirmation status"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="foods.food",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recognition_results",
                        to="images.uploadedimage",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score"],
            },
        ),
        migrations.AddIndex(
            model_name="uploadedimage",
            index=models.Index(fields=["user"], name="images_uplo_user_id_64ad97_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadedimage",
            index=models.Index(
                fields=["processing_status"], name="images_uplo_process_b77928_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodrecognitionresult",
            index=models.Index(fields=["image"], name="images_food_image_i_cb7c4c_idx"),
        ),
    ]
